name: Build
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build-app:
    runs-on: ubuntu-latest
    env:
      API_URL: ${{ secrets.API_URL }}
      FACEBOOK_APP_ID: ${{ secrets.FACEBOOK_APP_ID }}
      IMGBB_API_KEY: ${{ secrets.IMGBB_API_KEY }}
      EAS_PROJECT_ID: ${{ secrets.EAS_PROJECT_ID }}
    defaults:
      run:
        working-directory: ./mobile
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: "17"

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build android
        run: eas build -p android --profile preview --local --non-interactive --output "messenger-clone.apk"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ./mobile/messenger-clone.apk

      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        id: create_release
        with:
          repo_token: "${{ github.token }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest build"

      - name: Upload artifact to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./mobile/messenger-clone.apk
          asset_name: messenger-clone.apk
          asset_content_type: application/vnd.android.package-archive
