name: Build
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build-app:
    runs-on: ubuntu-latest
    env:
      EAS_PROJECT_ID: ${{ secrets.EAS_PROJECT_ID }}
    defaults:
      run:
        working-directory: ./mobile
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: "17"

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build android
        run: eas build -p android --profile preview --local --non-interactive --output "messenger-clone.apk"

      - uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ./mobile/messenger-clone.apk
